logging:
  level:
    org:
      springframework:
        jdbc: debug
        beans: error
        context: error
        kafka: error
      apache:
        kafka: error
    com:
      zaxxer:
        hikari: error
    liquibase: error
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss
