spring:
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-${random.uuid}
    security:
      protocol: PLAINTEXT
    admin:
      ssl:
        trust-store-type: NONE
    topics:
      user-csv-data-topic: user-csv-data
    bootstrap-servers: http://localhost:9092